sudo: required

services:
  - docker

script:
  - ./build.sh
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  - docker push ramseykhalaf/docker-php-demo
  - docker logout
